In [28]:
import numpy as np
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [7]:

THETA = np.radians(-90)

ROT_X_CW = lambda theta : np.array([[1,0,0],[0,np.cos(theta),-np.sin(theta)],[0,np.sin(theta),np.cos(theta)]]) # rotate clockwise around x
ROT_Y_CW = lambda theta : np.array([[np.cos(theta),0,np.sin(theta)],[0,1,0],[-np.sin(theta),0,np.cos(theta)]]) # rotate clockwise around y
ROT_Z_CW = lambda theta : np.array([[np.cos(theta),-np.sin(theta),0],[np.sin(theta),np.cos(theta),0],[0,0,1]]) # rotate clockwise around z


In [2]:
lst = []
for i in [-1,0,1]:
            for j in [-1,0,1]:
                for k in [-1,0,1]:
                    coords = np.array([[i],[j],[k]])
                    lst.append(coords)

In [6]:
lst = np.array(lst)

In [14]:
print(lst[0])
rot_lst = ROT_X_CW(THETA) @ lst
print(rot_lst[0])

[[-1]
 [-1]
 [-1]]
[[-1.]
 [-1.]
 [ 1.]]


In [24]:
print(rot_lst[0])
print(list(map(int,rot_lst[0])))

[[-1.]
 [-1.]
 [ 1.]]
[-1, -1, 0]


In [21]:
int(1.)

1